name: Workflow for Liatrio Take Home Assignment 

on:
  push:
    branches: ["main", "TestGHA"]

jobs: 

  build-test:

    runs-on: ubuntu-latest

    environment: Liatrio

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t liatrio .

      - name: Run Docker container
        run: docker run -d -p 80:80 liatrio

      - name: Run Liatrio tests
        uses: liatrio/github-actions/apprentice-action@v1.0.0

  release:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  push-deploy:
    runs-on: ubuntu-latest
    needs: release
    if: needs.build-test-push.outputs.new_release_published == 'true'

    steps:
      - name: "test"
        run: echo "hello!"