name: Workflow for Liatrio Take Home Assignment 

on:
  push:
    branches: ["main", "TestGHA"]

jobs: 
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t liatrio .

      - name: Run Docker container
        run: docker run -d -p 80:80 liatrio

      - name: Run Liatrio tests
        uses: liatrio/github-actions/apprentice-action@v1.0.0

  create-release-version:
    runs-on: ubuntu-latest
    needs: build-test
    outputs:
      version: ${{ steps.version.outputs.test }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Save version for Docker tag
        id: version
        run: |
          VERSION="${{ needs.create-release-version.outputs.new_release_version }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
  
  push-deploy:
    runs-on: ubuntu-latest
    needs: create-release-version

    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Push Docker image to Docker Hub
        run: |
          docker tag liatrio ${{ secrets.DOCKER_USERNAME }}/liatrio:${{ needs.create-release-version.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/liatrio:${{ needs.create-release-version.outputs.version }}

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'liatrio'
          region: us-west1
          image: 'docker.io/${{ secrets.DOCKER_USERNAME }}/liatrio:${{ needs.create-release-version.outputs.version }}'

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'