name: CI for Apprentice Assignment

on:
  push:
    branches: ["main"]

jobs: 
  build:
    container:
      image: node:16-alpine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: |
          echo "building image"
          docker build -t express-app:latest .
          docker save express-app:latest -o express-app.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: express-app.tar
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i express-app.tar

      - name: Run tests using apprentice-action
        uses: liatrio/github-actions/apprentice-action@v1.0.0
        with:
          image: express-app:latest
          