name: Workflow for Liatrio Take Home Assignment 

on:
  push:
    branches: ["main", "TestGHA"]

jobs: 

  build-test-push:

    permissions:
      contents: 'write'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Semantic Release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog
      
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Run Semantic Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(npx semantic-release | tee /dev/stderr | grep -oP "Published release: \K(v[0-9]+\.[0-9]+\.[0-9]+)")
          echo "NEW_VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Debug New Version
        run: echo "The new version released is ${{ env.NEW_VERSION }}"
      